name: Deploy Backend

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set python version to 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: backend/pyproject.toml
      - name: Create and Start virtual environment and Install dependencies
        run: |
          cd backend
          python -m venv antenv
          source antenv/bin/activate
          pip install .
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          include-hidden-files: true
          path: backend
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D9F53D9F7C541D09A4B2DFE02BF73FE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_979BA1A83A594871AB538A4ABD5B77AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_64C427212DE342E4B807FF8A9FA20C18 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "ability-api"
          slot-name: "Production"
